# Generated by Django 4.2.5 on 2023-09-25 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_director_remove_actor_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='slug',
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
